framework:
    secret: "%env(APP_SECRET)%"

    trusted_proxies: "127.0.0.1,REMOTE_ADDR"
    trusted_headers:
        [
            "x-forwarded-for",
            "x-forwarded-host",
            "x-forwarded-proto",
            "x-forwarded-port",
        ]

    csrf_protection: true

    session:
        cookie_secure: auto
        cookie_samesite: lax
        cookie_httponly: true

    http_method_override: false

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
