<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261006120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Offres de la page Services, gérables depuis le back-office (avec les 4 offres de départ)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE offer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(120) NOT NULL, summary VARCHAR(255) NOT NULL, items TEXT DEFAULT NULL, price_label VARCHAR(120) NOT NULL, note VARCHAR(255) DEFAULT NULL, icon VARCHAR(60) NOT NULL, position INT NOT NULL, active BOOLEAN NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');

        $this->addSql(
            'INSERT INTO offer (title, summary, items, price_label, note, icon, position, active, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, true, NOW())',
            ['Site internet', 'Un site rapide, à votre image, que vous mettez à jour vous-même.', "Essentiel : 1 à 3 pages, contact, lien vers votre fiche Google — 650 €\nVitrine : jusqu'à 6 pages, galerie, actualités — 950 €\nAvec réservation ou annonces en ligne — dès 1 900 €\nHébergement, sauvegardes, sécurité et 30 min de modifications par mois", 'dès 650 € + 35 € par mois', 'Associations : 30 € par mois', 'bi-window', 10]
        );
        $this->addSql(
            'INSERT INTO offer (title, summary, items, price_label, note, icon, position, active, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, true, NOW())',
            ['Avis Google clé en main', 'Vos clients lisent vos avis, et surtout vos réponses. Je m\'en occupe.', "Une réponse personnalisée à chaque avis sous 48 heures, avec votre ton et votre signature\nUn QR code à poser en caisse pour obtenir plus d'avis\nUne alerte immédiate en cas d'avis négatif\nUn bilan chaque mois : nombre d'avis, note, réponses", '29 € par mois', 'Vous restez propriétaire de votre fiche et pouvez me retirer l\'accès en un clic.', 'bi-star-half', 20]
        );
        $this->addSql(
            'INSERT INTO offer (title, summary, items, price_label, note, icon, position, active, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, true, NOW())',
            ['Fiche Google entretenue', 'Une fiche à jour, c\'est plus de clients qui vous trouvent sur Google Maps.', "Horaires des jours fériés et des vacances, toujours justes\n2 publications par mois : nouveautés, événements, offres\nPhotos, description et catégories optimisées", '39 € par mois', 'Avec les avis Google : 59 € par mois', 'bi-geo-alt', 30]
        );
        $this->addSql(
            'INSERT INTO offer (title, summary, items, price_label, note, icon, position, active, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, true, NOW())',
            ['Maintenance de votre site WordPress', 'Votre site a été fait par quelqu\'un qui n\'est plus là ? Je le reprends en main.', "Mises à jour de WordPress et des extensions, sans casse\nSauvegardes automatiques et surveillance de la sécurité\n30 minutes de modifications chaque mois", '39 € par mois', 'Bilan de départ : 90 €', 'bi-shield-check', 40]
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE offer');
    }
}
