parameters:
    project_images_directory: "%kernel.project_dir%/public/image/portfolio_media"

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Service\FileUploader:
        arguments:
            $targetDirectory: "%project_images_directory%"

    App\:
        resource: "../src/*"
        exclude: "../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php,Service/FileUploader.php}"
